# Generated by Django 5.2.16 on 2026-08-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=200)),
                ('purpose', models.CharField(choices=[('wallet', 'Wallet'), ('held_funds', 'Held funds')], max_length=500, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(choices=[('wallet_topup', 'Wallet topup'), ('wallet_payment', 'Wallet payment'), ('fee_charge', 'Fee charge'), ('refund', 'Refund')], max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='ledger_entr_account_dfa3c4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='entry_amount_nonzero')],
            },
        ),
    ]
