# Generated by Django 5.2.16 on 2026-08-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
           sql = """CREATE OR REPLACE FUNCTION check_entries_balance()
            RETURNS TRIGGER AS $$
            BEGIN
                IF (SELECT COALESCE(SUM(amount), 0)
                    FROM ledger_entry
                    WHERE transaction_id = NEW.transaction_id) <> 0 THEN
                    RAISE EXCEPTION 'Entries for transaction % do not sum to zero', NEW.transaction_id;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE CONSTRAINT TRIGGER entries_balance_check
            AFTER INSERT ON ledger_entry
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION check_entries_balance();
            """,
            reverse_sql = """
                    DROP TRIGGER IF EXISTS entries_balance_check ON ledger_entry;
                    DROP FUNCTION IF EXISTS check_entries_balance();
                """,
        )
    ]
