# Generated by Django 5.2.16 on 2026-08-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_add_balance_trigger'),
    ]

    operations = [
        migrations.RunSQL(
                   sql = """CREATE OR REPLACE FUNCTION prevent_entry_modification()
                            RETURNS TRIGGER AS $$
                            BEGIN
                                RAISE EXCEPTION 'Entries are immutable and cannot be modified or deleted';
                            END;
                            $$ LANGUAGE plpgsql;

                            CREATE TRIGGER entry_no_update
                            BEFORE UPDATE OR DELETE ON ledger_entry
                            FOR EACH ROW
                            EXECUTE FUNCTION prevent_entry_modification();
                        """,
                    reverse_sql = """
                            DROP TRIGGER IF EXISTS entry_no_update ON ledger_entry;
                            DROP FUNCTION IF EXISTS prevent_entry_modification();
                        """
                )
    ]
