# Generated by Django 5.2.16 on 2026-09-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_idempotencykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('transaction_created', 'Transaction created'), ('transaction_reversed', 'Transaction reversed')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.transaction')),
            ],
        ),
    ]
