# Generated by Django 5.2.16 on 2026-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_ledgerauditevent'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """CREATE OR REPLACE FUNCTION prevent_audit_modification()
                    RETURNS TRIGGER AS $$
                    BEGIN
                        RAISE EXCEPTION 'Audit events are immutable and cannot be modified or deleted';
                    END;
                    $$ LANGUAGE plpgsql;

                    CREATE TRIGGER audit_entry_no_update
                    BEFORE UPDATE OR DELETE ON ledger_ledgerauditevent
                    FOR EACH ROW
                    EXECUTE FUNCTION prevent_audit_modification();
                """,
            reverse_sql = """
                    DROP TRIGGER IF EXISTS audit_entry_no_update ON ledger_ledgerauditevent;
                    DROP FUNCTION IF EXISTS prevent_audit_modification();
                """
        )
    ]