# Generated by Django 5.2.16 on 2026-10-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_webhooknonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_ref', models.CharField(max_length=200, unique=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_records', to='ledger.transaction')),
            ],
        ),
    ]
