# Generated by Django 5.2.16 on 2026-10-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_providerrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch_type', models.CharField(choices=[('missing_in_provider', 'Missing in provider'), ('missing_in_ledger', 'Missing in ledger'), ('amount_mismatch', 'Amount mismatch')], max_length=50)),
                ('provider_ref', models.CharField(max_length=200, null=True)),
                ('ledger_amount', models.BigIntegerField(null=True)),
                ('provider_amount', models.BigIntegerField(null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_mismatch', to='ledger.transaction')),
            ],
        ),
    ]
