# Generated by Django 5.2.16 on 2026-09-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('ledger', '0004_idempotencykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.BigIntegerField()),
                ('vendor', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], default='pending', max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='agents.agent')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spend_requests', to='ledger.transaction')),
            ],
        ),
    ]
