# Generated by Django 5.2.16 on 2026-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendrequest',
            name='policy_decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
