# Generated by Django 5.2.16 on 2026-09-07 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.BigIntegerField()),
                ('monthly_limit', models.BigIntegerField()),
                ('per_txn_limit', models.BigIntegerField()),
                ('auto_approve_threshold', models.BigIntegerField()),
                ('spent_today', models.BigIntegerField(default=0)),
                ('spent_this_month', models.BigIntegerField(default=0)),
                ('vendor_allowlist', models.JSONField(default=list)),
                ('currency', models.CharField(max_length=3)),
                ('last_daily_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_monthly_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='agents.agent')),
            ],
        ),
    ]
